//! 构建期把 protocol/definition/*.json 以 include_str! 内嵌进二进制。
//!
//! 运行期一次性解析并编译为编解码计划（registry::Registry::build），
//! 构建期不依赖任何 JSON 解析——只生成文件清单，保证离线可构建。

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let dir = Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/definition"));
    let mut files: Vec<_> = std::fs::read_dir(dir)
        .expect("protocol/definition directory must exist")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    files.sort();

    let mut out = String::from("// @generated by build.rs — do not edit\n");
    out.push_str("pub static DEFINITIONS: &[(&str, &str)] = &[\n");
    for f in &files {
        let stem = f.file_stem().unwrap().to_str().unwrap();
        // include_str! 相对 include! 所在文件（OUT_DIR）解析，必须用绝对路径
        writeln!(&mut out, "    ({stem:?}, include_str!({:?})),", f.to_str().unwrap()).unwrap();
    }
    out.push_str("];\n");

    let out_path = Path::new(&std::env::var("OUT_DIR").unwrap()).join("definitions.rs");
    std::fs::write(out_path, out).unwrap();
}
